on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Run JMeter Tests
        uses: ./
        with:
          test-plan-path: ./testPlanjmx.jmx
          args: ""
          
      - name: Upload Results
        uses: actions/checkout@v1
        with:
          name: jmeter-results
          path: result.jtl
